---

name: Maven deploy

on:
  push:
    branches: [main,release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # for Codecov
          fetch-depth: 2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Maven deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./mvnw -B javadoc:jar source:jar deploy
      - uses: codecov/codecov-action@v5
      - uses: actions/upload-artifact@v4
        with:
          name: locks
          path: target/locks-*.jar
